package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class CommPrices 
{

protected int Id   = 0;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String Market ;

/** Field mapping. **/
protected String Commodity ;

/** Field mapping. **/
protected String Variety ;

/** Field mapping. **/
protected String Units ;

/** Field mapping. **/
protected int MinPrice ;

/** Field mapping. **/
protected int MaxPrice ;

/** Field mapping. **/
protected int ModalPrice ;

/** Field mapping. **/
protected String UnitOfPrice ,pincode;

public String getPincode() {
	return pincode;
}
public void setPincode(String pincode) {
	this.pincode = pincode;
}
/** Field mapping. **/
protected Date Date ;

public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getMarket()
{
  return Market;
}
public void setMarket(final String Market)
{
  this.Market = Market;
}
public String getCommodity()
{
  return Commodity;
}
public void setCommodity(final String Commodity)
{
  this.Commodity = Commodity;
}
public String getVariety()
{
  return Variety;
}
public void setVariety(final String Variety)
{
  this.Variety = Variety;
}
public String getUnits()
{
  return Units;
}
public void setUnits(final String Units)
{
  this.Units = Units;
}
public int getMinPrice()
{
  return MinPrice;
}
public void setMinPrice(final int MinPrice)
{
  this.MinPrice = MinPrice;
}
public int getMaxPrice()
{
  return MaxPrice;
}
public void setMaxPrice(final int MaxPrice)
{
  this.MaxPrice = MaxPrice;
}
public int getModalPrice()
{
  return ModalPrice;
}
public void setModalPrice(final int ModalPrice)
{
  this.ModalPrice = ModalPrice;
}
public String getUnitOfPrice()
{
  return UnitOfPrice;
}
public void setUnitOfPrice(final String UnitOfPrice)
{
  this.UnitOfPrice = UnitOfPrice;
}
public Date getDate()
{
  return Date;
}
public void setDate(final Date Date)
{
  this.Date = Date;
}

}