package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class FarRegs 
{
protected int Id   = 0;

/** Field mapping. **/
protected String FirstName ;

/** Field mapping. **/
protected String LastName ;

/** Field mapping. **/
protected String Dob ;

/** Field mapping. **/
protected String Mobile ;

/** Field mapping. **/
protected String Aadhar ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected String Village ;

/** Field mapping. **/
protected String Mandal ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String Pincode ;

/** Field mapping. **/
protected String CropType ;

/** Field mapping. **/
protected String Crop1 ;

/** Field mapping. **/
protected String Crop2 ;

/** Field mapping. **/
protected String Crop3 ;

/** Field mapping. **/
protected String Crop4 ;

/** Field mapping. **/
protected String Crop5 ;

/** Field mapping. **/
//protected String AddCrop ;

/** Field mapping. **/
protected String Vegetables ;

/** Field mapping. **/
protected String Veg1 ;

/** Field mapping. **/
protected String Veg2 ;

/** Field mapping. **/
protected String Veg3 ;

/** Field mapping. **/
protected String Veg4 ;

/** Field mapping. **/
protected String Veg5 ;

/** Field mapping. **/
protected String Veg6 ;

/** Field mapping. **/
protected String Veg7 ;

/** Field mapping. **/
protected String Veg8 ;

/** Field mapping. **/
//protected String AddVeg ;

/** Field mapping. **/
protected String AniHus ;

/** Field mapping. **/
protected String AniHus1 ;

/** Field mapping. **/
protected String AniHus2 ;

/** Field mapping. **/
protected String AniHus3 ;

/** Field mapping. **/
//protected String AddAniHus ;

/** Field mapping. **/
protected String Dairy ;

/** Field mapping. **/
protected String Dairy1 ;

/** Field mapping. **/
protected String Dairy2 ;

/** Field mapping. **/
protected String Dairy3 ;

/** Field mapping. **/
//protected String AddDairy ;

/** Field mapping. **/
protected String TokenId ;

/** Field mapping. **/
protected Date DateOfReg ;

protected String Ccode ;



public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getFirstName()
{
  return FirstName;
}
public void setFirstName(final String FirstName)
{
  this.FirstName = FirstName;
}
public String getLastName()
{
  return LastName;
}
public void setLastName(final String LastName)
{
  this.LastName = LastName;
}
public String getDob()
{
  return Dob;
}
public void setDob(final String Dob)
{
  this.Dob = Dob;
}
public String getMobile()
{
  return Mobile;
}
public void setMobile(final String Mobile)
{
  this.Mobile = Mobile;
}
public String getAadhar()
{
  return Aadhar;
}
public void setAadhar(final String Aadhar)
{
  this.Aadhar = Aadhar;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public String getVillage()
{
  return Village;
}
public void setVillage(final String Village)
{
  this.Village = Village;
}
public String getMandal()
{
  return Mandal;
}
public void setMandal(final String Mandal)
{
  this.Mandal = Mandal;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}

public String getPincode() {
	return Pincode;
}
public void setPincode(String pincode) {
	Pincode = pincode;
}
public String getCropType()
{
  return CropType;
}
public void setCropType(final String CropType)
{
  this.CropType = CropType;
}
public String getCrop1()
{
  return Crop1;
}
public void setCrop1(final String Crop1)
{
  this.Crop1 = Crop1;
}
public String getCrop2()
{
  return Crop2;
}
public void setCrop2(final String Crop2)
{
  this.Crop2 = Crop2;
}
public String getCrop3()
{
  return Crop3;
}
public void setCrop3(final String Crop3)
{
  this.Crop3 = Crop3;
}
public String getCrop4()
{
  return Crop4;
}
public void setCrop4(final String Crop4)
{
  this.Crop4 = Crop4;
}
public String getCrop5()
{
  return Crop5;
}
public void setCrop5(final String Crop5)
{
  this.Crop5 = Crop5;
}

public String getVegetables()
{
  return Vegetables;
}
public void setVegetables(final String Vegetables)
{
  this.Vegetables = Vegetables;
}
public String getVeg1()
{
  return Veg1;
}
public void setVeg1(final String Veg1)
{
  this.Veg1 = Veg1;
}
public String getVeg2()
{
  return Veg2;
}
public void setVeg2(final String Veg2)
{
  this.Veg2 = Veg2;
}
public String getVeg3()
{
  return Veg3;
}
public void setVeg3(final String Veg3)
{
  this.Veg3 = Veg3;
}
public String getVeg4()
{
  return Veg4;
}
public void setVeg4(final String Veg4)
{
  this.Veg4 = Veg4;
}
public String getVeg5()
{
  return Veg5;
}
public void setVeg5(final String Veg5)
{
  this.Veg5 = Veg5;
}
public String getVeg6()
{
  return Veg6;
}
public void setVeg6(final String Veg6)
{
  this.Veg6 = Veg6;
}
public String getVeg7()
{
  return Veg7;
}
public void setVeg7(final String Veg7)
{
  this.Veg7 = Veg7;
}
public String getVeg8()
{
  return Veg8;
}
public void setVeg8(final String Veg8)
{
  this.Veg8 = Veg8;
}

public String getAniHus()
{
  return AniHus;
}
public void setAniHus(final String AniHus)
{
  this.AniHus = AniHus;
}
public String getAniHus1()
{
  return AniHus1;
}
public void setAniHus1(final String AniHus1)
{
  this.AniHus1 = AniHus1;
}
public String getAniHus2()
{
  return AniHus2;
}
public void setAniHus2(final String AniHus2)
{
  this.AniHus2 = AniHus2;
}
public String getAniHus3()
{
  return AniHus3;
}
public void setAniHus3(final String AniHus3)
{
  this.AniHus3 = AniHus3;
}

public String getDairy()
{
  return Dairy;
}
public void setDairy(final String Dairy)
{
  this.Dairy = Dairy;
}
public String getDairy1()
{
  return Dairy1;
}
public void setDairy1(final String Dairy1)
{
  this.Dairy1 = Dairy1;
}
public String getDairy2()
{
  return Dairy2;
}
public void setDairy2(final String Dairy2)
{
  this.Dairy2 = Dairy2;
}
public String getDairy3()
{
  return Dairy3;
}
public void setDairy3(final String Dairy3)
{
  this.Dairy3 = Dairy3;
}

public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}
public Date getDateOfReg()
{
  return DateOfReg;
}
public void setDateOfReg(final Date DateOfReg)
{
  this.DateOfReg = DateOfReg;
}




public String getCcode() {
	return Ccode;
}
public void setCcode(String ccode) {
	Ccode = ccode;
}
@Override
public String toString() {
	return "FarRegs [Id=" + Id + ", FirstName=" + FirstName + ", LastName=" + LastName + ", Dob=" + Dob + ", Mobile="
			+ Mobile + ", Aadhar=" + Aadhar + ", Address=" + Address + ", Village=" + Village + ", Mandal=" + Mandal
			+ ", District=" + District + ", State=" + State + ", Pincode=" + Pincode + ", CropType=" + CropType
			+ ", Crop1=" + Crop1 + ", Crop2=" + Crop2 + ", Crop3=" + Crop3 + ", Crop4=" + Crop4 + ", Crop5=" + Crop5
			+ ", Vegetables=" + Vegetables + ", Veg1=" + Veg1 + ", Veg2=" + Veg2 + ", Veg3=" + Veg3 + ", Veg4=" + Veg4
			+ ", Veg5=" + Veg5 + ", Veg6=" + Veg6 + ", Veg7=" + Veg7 + ", Veg8=" + Veg8 + ", AniHus=" + AniHus
			+ ", AniHus1=" + AniHus1 + ", AniHus2=" + AniHus2 + ", AniHus3=" + AniHus3 + ", Dairy=" + Dairy
			+ ", Dairy1=" + Dairy1 + ", Dairy2=" + Dairy2 + ", Dairy3=" + Dairy3 + ", TokenId=" + TokenId
			+ ", DateOfReg=" + DateOfReg + ", Ccode=" + Ccode + "]";
}








}