package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class Input 
{

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String Category ;

/** Field mapping. **/
protected int Count ;

/** Field mapping. **/
protected String Input ;

public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getCategory()
{
  return Category;
}
public void setCategory(final String Category)
{
  this.Category = Category;
}
public int getCount()
{
  return Count;
}
public void setCount(final int Count)
{
  this.Count = Count;
}
public String getInput()
{
  return Input;
}
public void setInput(final String Input)
{
  this.Input = Input;
}

}