package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class LogisticsReg 
{
		 /** Field mapping. **/
protected int Id   = 0;

/** Field mapping. **/
protected String FirstName ;

/** Field mapping. **/
protected String LastName ;

/** Field mapping. **/
protected String CompanyName ;

/** Field mapping. **/
protected String DateOfIncorp ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected String Status ;

/** Field mapping. **/
protected String Village ;

/** Field mapping. **/
protected String Mandal ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected int Pincode ;

/** Field mapping. **/
protected String Mobile ;

/** Field mapping. **/
protected String Email ;

/** Field mapping. **/
protected String VehicleType ;

/** Field mapping. **/
protected String VehicleCapacity ;

/** Field mapping. **/
protected String VehicleCapcityUnits ;

/** Field mapping. **/
protected String TokenId ;

/** Field mapping. **/
protected Date DateOfReg ;

protected String Ccode ;

protected String MyPlan ;

protected String Distance;


public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getFirstName()
{
  return FirstName;
}
public void setFirstName(final String FirstName)
{
  this.FirstName = FirstName;
}
public String getLastName()
{
  return LastName;
}
public void setLastName(final String LastName)
{
  this.LastName = LastName;
}
public String getCompanyName()
{
  return CompanyName;
}
public void setCompanyName(final String CompanyName)
{
  this.CompanyName = CompanyName;
}
public String getDateOfIncorp()
{
  return DateOfIncorp;
}
public void setDateOfIncorp(final String DateOfIncorp)
{
  this.DateOfIncorp = DateOfIncorp;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public String getStatus()
{
  return Status;
}
public void setStatus(final String Status)
{
  this.Status = Status;
}
public String getVillage()
{
  return Village;
}
public void setVillage(final String Village)
{
  this.Village = Village;
}
public String getMandal()
{
  return Mandal;
}
public void setMandal(final String Mandal)
{
  this.Mandal = Mandal;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public int getPincode()
{
  return Pincode;
}
public void setPincode(final int Pincode)
{
  this.Pincode = Pincode;
}
public String getMobile()
{
  return Mobile;
}
public void setMobile(final String Mobile)
{
  this.Mobile = Mobile;
}
public String getEmail()
{
  return Email;
}
public void setEmail(final String Email)
{
  this.Email = Email;
}
public String getVehicleType()
{
  return VehicleType;
}
public void setVehicleType(final String VehicleType)
{
  this.VehicleType = VehicleType;
}
public String getVehicleCapacity()
{
  return VehicleCapacity;
}
public void setVehicleCapacity(final String VehicleCapacity)
{
  this.VehicleCapacity = VehicleCapacity;
}
public String getVehicleCapcityUnits()
{
  return VehicleCapcityUnits;
}
public void setVehicleCapcityUnits(final String VehicleCapcityUnits)
{
  this.VehicleCapcityUnits = VehicleCapcityUnits;
}
public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}
public Date getDateOfReg()
{
  return DateOfReg;
}
public void setDateOfReg(final Date DateOfReg)
{
  this.DateOfReg = DateOfReg;
}




public String getCcode() {
	return Ccode;
}
public void setCcode(String ccode) {
	Ccode = ccode;
}
public String getMyPlan() {
	return MyPlan;
}
public void setMyPlan(String myPlan) {
	MyPlan = myPlan;
}


public String getDistance() {
	return Distance;
}
public void setDistance(String distance) {
	Distance = distance;
}
@Override
public String toString() {
	return "LogisticsReg [Id=" + Id + ", FirstName=" + FirstName + ", LastName=" + LastName + ", CompanyName="
			+ CompanyName + ", DateOfIncorp=" + DateOfIncorp + ", Address=" + Address + ", Status=" + Status
			+ ", Village=" + Village + ", Mandal=" + Mandal + ", District=" + District + ", State=" + State
			+ ", Pincode=" + Pincode + ", Mobile=" + Mobile + ", Email=" + Email + ", VehicleType=" + VehicleType
			+ ", VehicleCapacity=" + VehicleCapacity + ", VehicleCapcityUnits=" + VehicleCapcityUnits + ", TokenId="
			+ TokenId + ", DateOfReg=" + DateOfReg + ", Ccode=" + Ccode + ", MyPlan=" + MyPlan + "]";
}









}