package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class MasAh 
{

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String Animal ;

/** Field mapping. **/
protected String Breed ;

public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getAnimal()
{
  return Animal;
}
public void setAnimal(final String Animal)
{
  this.Animal = Animal;
}
public String getBreed()
{
  return Breed;
}
public void setBreed(final String Breed)
{
  this.Breed = Breed;
}

}