package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class MasCom 
{

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String Commodity ;

/** Field mapping. **/
protected String LocalName ;

/** Field mapping. **/
protected String Variety ;

public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getCommodity()
{
  return Commodity;
}
public void setCommodity(final String Commodity)
{
  this.Commodity = Commodity;
}
public String getLocalName()
{
  return LocalName;
}
public void setLocalName(final String LocalName)
{
  this.LocalName = LocalName;
}
public String getVariety()
{
  return Variety;
}
public void setVariety(final String Variety)
{
  this.Variety = Variety;
}

}