package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class MasDairy 
{

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String ProductName ;

/** Field mapping. **/
protected String Variety ;

public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getProductName()
{
  return ProductName;
}
public void setProductName(final String ProductName)
{
  this.ProductName = ProductName;
}
public String getVariety()
{
  return Variety;
}
public void setVariety(final String Variety)
{
  this.Variety = Variety;
}

}