package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class MasVeg 
{

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String Vegetable ;

/** Field mapping. **/
protected String LocalName ;

public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getVegetable()
{
  return Vegetable;
}
public void setVegetable(final String Vegetable)
{
  this.Vegetable = Vegetable;
}
public String getLocalName()
{
  return LocalName;
}
public void setLocalName(final String LocalName)
{
  this.LocalName = LocalName;
}

}