package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class Pincodedata 
{

/** Field mapping. **/
protected int Id ;

/** Field mapping. **/
protected String VillageName ;

/** Field mapping. **/
protected String Pincode ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getVillageName()
{
  return VillageName;
}
public void setVillageName(final String VillageName)
{
  this.VillageName = VillageName;
}
public String getPincode()
{
  return Pincode;
}
public void setPincode(final String Pincode)
{
  this.Pincode = Pincode;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}

}