package com.aurospaces.neighbourhood.bean;


import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 *
 * @author autogenerated
 */



public class ProcReg 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
protected int Id   = 0;

/** Field mapping. **/
protected String TokenId ;

/** Field mapping. **/
protected String FirstName ;

/** Field mapping. **/
protected String LastName ;

/** Field mapping. **/
protected String CompanyName ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected String Village ;

/** Field mapping. **/
protected String Mandal ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String Pincode ;

/** Field mapping. **/
protected String Email ;

/** Field mapping. **/
protected String Mobile ;

/** Field mapping. **/
protected Date DateOfIncorp ;

/** Field mapping. **/
protected String GSTNumber ;

/** Field mapping. **/
protected String Status ;

/** Field mapping. **/
protected String RawMaterial ;

/** Field mapping. **/
protected String Raw1 ;

/** Field mapping. **/
protected String Raw2 ;

/** Field mapping. **/
protected String Raw3 ;

/** Field mapping. **/
protected String AddRaw ;

/** Field mapping. **/
protected String FinProduct ;

/** Field mapping. **/
protected String Packaging ;

/** Field mapping. **/
protected Date DateOfReg ;

public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}
public String getFirstName()
{
  return FirstName;
}
public void setFirstName(final String FirstName)
{
  this.FirstName = FirstName;
}
public String getLastName()
{
  return LastName;
}
public void setLastName(final String LastName)
{
  this.LastName = LastName;
}
public String getCompanyName()
{
  return CompanyName;
}
public void setCompanyName(final String CompanyName)
{
  this.CompanyName = CompanyName;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public String getVillage()
{
  return Village;
}
public void setVillage(final String Village)
{
  this.Village = Village;
}
public String getMandal()
{
  return Mandal;
}
public void setMandal(final String Mandal)
{
  this.Mandal = Mandal;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getPincode()
{
  return Pincode;
}
public void setPincode(final String Pincode)
{
  this.Pincode = Pincode;
}
public String getEmail()
{
  return Email;
}
public void setEmail(final String Email)
{
  this.Email = Email;
}
public String getMobile()
{
  return Mobile;
}
public void setMobile(final String Mobile)
{
  this.Mobile = Mobile;
}
public Date getDateOfIncorp()
{
  return DateOfIncorp;
}
public void setDateOfIncorp(final Date DateOfIncorp)
{
  this.DateOfIncorp = DateOfIncorp;
}
public String getGSTNumber()
{
  return GSTNumber;
}
public void setGSTNumber(final String GSTNumber)
{
  this.GSTNumber = GSTNumber;
}
public String getStatus()
{
  return Status;
}
public void setStatus(final String Status)
{
  this.Status = Status;
}
public String getRawMaterial()
{
  return RawMaterial;
}
public void setRawMaterial(final String RawMaterial)
{
  this.RawMaterial = RawMaterial;
}
public String getRaw1()
{
  return Raw1;
}
public void setRaw1(final String Raw1)
{
  this.Raw1 = Raw1;
}
public String getRaw2()
{
  return Raw2;
}
public void setRaw2(final String Raw2)
{
  this.Raw2 = Raw2;
}
public String getRaw3()
{
  return Raw3;
}
public void setRaw3(final String Raw3)
{
  this.Raw3 = Raw3;
}
public String getAddRaw()
{
  return AddRaw;
}
public void setAddRaw(final String AddRaw)
{
  this.AddRaw = AddRaw;
}
public String getFinProduct()
{
  return FinProduct;
}
public void setFinProduct(final String FinProduct)
{
  this.FinProduct = FinProduct;
}
public String getPackaging()
{
  return Packaging;
}
public void setPackaging(final String Packaging)
{
  this.Packaging = Packaging;
}
public Date getDateOfReg()
{
  return DateOfReg;
}
public void setDateOfReg(final Date DateOfReg)
{
  this.DateOfReg = DateOfReg;
}

}