package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class Stor 
{

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String StorageName ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected int Pincode ;

/** Field mapping. **/
protected int capacity ;

public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getStorageName()
{
  return StorageName;
}
public void setStorageName(final String StorageName)
{
  this.StorageName = StorageName;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public int getPincode()
{
  return Pincode;
}
public void setPincode(final int Pincode)
{
  this.Pincode = Pincode;
}
public int getCapacity()
{
  return capacity;
}
public void setCapacity(final int capacity)
{
  this.capacity = capacity;
}

}