package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class StorageReg 
{

		 /** Field mapping. **/
protected int Id   = 0;

/** Field mapping. **/
protected String TokenId ;

/** Field mapping. **/
protected String FirstName ;

/** Field mapping. **/
protected String LastName ;

/** Field mapping. **/
protected String CompanyName ;

/** Field mapping. **/
protected String Status ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected String Village ;

/** Field mapping. **/
protected String Mandal ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected int Pincode ;

/** Field mapping. **/
protected String Email ;

/** Field mapping. **/
protected String Mobile ;

/** Field mapping. **/
protected String DateOfIncorp ;

/** Field mapping. **/
protected String GSTNumber ;

/** Field mapping. **/
protected String Crops ;

/** Field mapping. **/
protected String Vegetables ;

protected String aniHusbandry ;

/** Field mapping. **/
protected String Dairy ;

/** Field mapping. **/
protected String StorageCapacity ;

/** Field mapping. **/
protected String Units,strdateOfIncorp,distance ;

/** Field mapping. **/
protected Date DateOfReg ;


protected String Ccode ;

protected String MyPlan ;

public String getStrdateOfIncorp() {
	return strdateOfIncorp;
}
public void setStrdateOfIncorp(String strdateOfIncorp) {
	this.strdateOfIncorp = strdateOfIncorp;
}
public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}
public String getFirstName()
{
  return FirstName;
}
public void setFirstName(final String FirstName)
{
  this.FirstName = FirstName;
}
public String getLastName()
{
  return LastName;
}
public void setLastName(final String LastName)
{
  this.LastName = LastName;
}
public String getCompanyName()
{
  return CompanyName;
}
public void setCompanyName(final String CompanyName)
{
  this.CompanyName = CompanyName;
}
public String getStatus()
{
  return Status;
}
public void setStatus(final String Status)
{
  this.Status = Status;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public String getVillage()
{
  return Village;
}
public void setVillage(final String Village)
{
  this.Village = Village;
}
public String getMandal()
{
  return Mandal;
}
public void setMandal(final String Mandal)
{
  this.Mandal = Mandal;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public int getPincode()
{
  return Pincode;
}
public void setPincode(final int Pincode)
{
  this.Pincode = Pincode;
}
public String getEmail()
{
  return Email;
}
public void setEmail(final String Email)
{
  this.Email = Email;
}
public String getMobile()
{
  return Mobile;
}
public void setMobile(final String Mobile)
{
  this.Mobile = Mobile;
}

public String getGSTNumber()
{
  return GSTNumber;
}
public void setGSTNumber(final String GSTNumber)
{
  this.GSTNumber = GSTNumber;
}
public String getCrops()
{
  return Crops;
}
public void setCrops(final String Crops)
{
  this.Crops = Crops;
}
public String getVegetables()
{
  return Vegetables;
}
public void setVegetables(final String Vegetables)
{
  this.Vegetables = Vegetables;
}
public String getDairy()
{
  return Dairy;
}
public void setDairy(final String Dairy)
{
  this.Dairy = Dairy;
}
public String getStorageCapacity()
{
  return StorageCapacity;
}
public void setStorageCapacity(final String StorageCapacity)
{
  this.StorageCapacity = StorageCapacity;
}
public String getUnits()
{
  return Units;
}
public void setUnits(final String Units)
{
  this.Units = Units;
}
public Date getDateOfReg()
{
  return DateOfReg;
}
public void setDateOfReg(final Date DateOfReg)
{
  this.DateOfReg = DateOfReg;
}
public String getAniHusbandry() {
	return aniHusbandry;
}
public void setAniHusbandry(String aniHusbandry) {
	this.aniHusbandry = aniHusbandry;
}
public String getDistance() {
	return distance;
}
public void setDistance(String distance) {
	this.distance = distance;
}




public String getCcode() {
	return Ccode;
}
public void setCcode(String ccode) {
	Ccode = ccode;
}
public String getMyPlan() {
	return MyPlan;
}
public void setMyPlan(String myPlan) {
	MyPlan = myPlan;
}

public String getDateOfIncorp() {
	return DateOfIncorp;
}
public void setDateOfIncorp(String dateOfIncorp) {
	DateOfIncorp = dateOfIncorp;
}
@Override
public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((Address == null) ? 0 : Address.hashCode());
	result = prime * result + ((CompanyName == null) ? 0 : CompanyName.hashCode());
	result = prime * result + ((Crops == null) ? 0 : Crops.hashCode());
	result = prime * result + ((Dairy == null) ? 0 : Dairy.hashCode());
	result = prime * result + ((DateOfIncorp == null) ? 0 : DateOfIncorp.hashCode());
	result = prime * result + ((DateOfReg == null) ? 0 : DateOfReg.hashCode());
	result = prime * result + ((District == null) ? 0 : District.hashCode());
	result = prime * result + ((Email == null) ? 0 : Email.hashCode());
	result = prime * result + ((FirstName == null) ? 0 : FirstName.hashCode());
	result = prime * result + ((GSTNumber == null) ? 0 : GSTNumber.hashCode());
	result = prime * result + Id;
	result = prime * result + ((LastName == null) ? 0 : LastName.hashCode());
	result = prime * result + ((Mandal == null) ? 0 : Mandal.hashCode());
	result = prime * result + ((Mobile == null) ? 0 : Mobile.hashCode());
	result = prime * result + Pincode;
	result = prime * result + ((State == null) ? 0 : State.hashCode());
	result = prime * result + ((Status == null) ? 0 : Status.hashCode());
	result = prime * result + ((StorageCapacity == null) ? 0 : StorageCapacity.hashCode());
	result = prime * result + ((TokenId == null) ? 0 : TokenId.hashCode());
	result = prime * result + ((Units == null) ? 0 : Units.hashCode());
	result = prime * result + ((Vegetables == null) ? 0 : Vegetables.hashCode());
	result = prime * result + ((Village == null) ? 0 : Village.hashCode());
	result = prime * result + ((aniHusbandry == null) ? 0 : aniHusbandry.hashCode());
	result = prime * result + ((distance == null) ? 0 : distance.hashCode());
	result = prime * result + ((strdateOfIncorp == null) ? 0 : strdateOfIncorp.hashCode());
	return result;
}
@Override
public boolean equals(Object obj) {
	if (this == obj)
		return true;
	if (obj == null)
		return false;
	if (getClass() != obj.getClass())
		return false;
	StorageReg other = (StorageReg) obj;
	if (Address == null) {
		if (other.Address != null)
			return false;
	} else if (!Address.equals(other.Address))
		return false;
	if (CompanyName == null) {
		if (other.CompanyName != null)
			return false;
	} else if (!CompanyName.equals(other.CompanyName))
		return false;
	if (Crops == null) {
		if (other.Crops != null)
			return false;
	} else if (!Crops.equals(other.Crops))
		return false;
	if (Dairy == null) {
		if (other.Dairy != null)
			return false;
	} else if (!Dairy.equals(other.Dairy))
		return false;
	if (DateOfIncorp == null) {
		if (other.DateOfIncorp != null)
			return false;
	} else if (!DateOfIncorp.equals(other.DateOfIncorp))
		return false;
	if (DateOfReg == null) {
		if (other.DateOfReg != null)
			return false;
	} else if (!DateOfReg.equals(other.DateOfReg))
		return false;
	if (District == null) {
		if (other.District != null)
			return false;
	} else if (!District.equals(other.District))
		return false;
	if (Email == null) {
		if (other.Email != null)
			return false;
	} else if (!Email.equals(other.Email))
		return false;
	if (FirstName == null) {
		if (other.FirstName != null)
			return false;
	} else if (!FirstName.equals(other.FirstName))
		return false;
	if (GSTNumber == null) {
		if (other.GSTNumber != null)
			return false;
	} else if (!GSTNumber.equals(other.GSTNumber))
		return false;
	if (Id != other.Id)
		return false;
	if (LastName == null) {
		if (other.LastName != null)
			return false;
	} else if (!LastName.equals(other.LastName))
		return false;
	if (Mandal == null) {
		if (other.Mandal != null)
			return false;
	} else if (!Mandal.equals(other.Mandal))
		return false;
	if (Mobile == null) {
		if (other.Mobile != null)
			return false;
	} else if (!Mobile.equals(other.Mobile))
		return false;
	if (Pincode != other.Pincode)
		return false;
	if (State == null) {
		if (other.State != null)
			return false;
	} else if (!State.equals(other.State))
		return false;
	if (Status == null) {
		if (other.Status != null)
			return false;
	} else if (!Status.equals(other.Status))
		return false;
	if (StorageCapacity == null) {
		if (other.StorageCapacity != null)
			return false;
	} else if (!StorageCapacity.equals(other.StorageCapacity))
		return false;
	if (TokenId == null) {
		if (other.TokenId != null)
			return false;
	} else if (!TokenId.equals(other.TokenId))
		return false;
	if (Units == null) {
		if (other.Units != null)
			return false;
	} else if (!Units.equals(other.Units))
		return false;
	if (Vegetables == null) {
		if (other.Vegetables != null)
			return false;
	} else if (!Vegetables.equals(other.Vegetables))
		return false;
	if (Village == null) {
		if (other.Village != null)
			return false;
	} else if (!Village.equals(other.Village))
		return false;
	if (aniHusbandry == null) {
		if (other.aniHusbandry != null)
			return false;
	} else if (!aniHusbandry.equals(other.aniHusbandry))
		return false;
	if (distance == null) {
		if (other.distance != null)
			return false;
	} else if (!distance.equals(other.distance))
		return false;
	if (strdateOfIncorp == null) {
		if (other.strdateOfIncorp != null)
			return false;
	} else if (!strdateOfIncorp.equals(other.strdateOfIncorp))
		return false;
	return true;
}
@Override
public String toString() {
	return "StorageReg [Id=" + Id + ", TokenId=" + TokenId + ", FirstName=" + FirstName + ", LastName=" + LastName
			+ ", CompanyName=" + CompanyName + ", Status=" + Status + ", Address=" + Address + ", Village=" + Village
			+ ", Mandal=" + Mandal + ", District=" + District + ", State=" + State + ", Pincode=" + Pincode + ", Email="
			+ Email + ", Mobile=" + Mobile + ", DateOfIncorp=" + DateOfIncorp + ", GSTNumber=" + GSTNumber + ", Crops="
			+ Crops + ", Vegetables=" + Vegetables + ", aniHusbandry=" + aniHusbandry + ", Dairy=" + Dairy
			+ ", StorageCapacity=" + StorageCapacity + ", Units=" + Units + ", strdateOfIncorp=" + strdateOfIncorp
			+ ", distance=" + distance + ", DateOfReg=" + DateOfReg + ", Ccode=" + Ccode + ", MyPlan=" + MyPlan + "]";
}








}