package com.aurospaces.neighbourhood.bean;


import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;


/**
 *
 * @author autogenerated
 */



public class SupplierReg 
{

		 /** Field mapping. **/
protected int Id   = 0;

/** Field mapping. **/
protected String TokenId ;

/** Field mapping. **/
protected String FirstName ;

/** Field mapping. **/
protected String LastName ;

/** Field mapping. **/
protected String CompanyName ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected String Village ;

/** Field mapping. **/
protected String Mandal ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected int Pincode ;

/** Field mapping. **/
protected String Email ;

/** Field mapping. **/
protected String Mobile ;

/** Field mapping. **/
@JsonFormat(shape=JsonFormat.Shape.STRING,pattern="dd-MM-yyyy")
protected Date DateOfIncorp ;

/** Field mapping. **/
protected String GSTNumber ;

/** Field mapping. **/
protected String Status ;

/** Field mapping. **/
protected String Bio ;

/** Field mapping. **/
protected String Botanical ;

/** Field mapping. **/
protected String FarmMachinery ;

/** Field mapping. **/
protected String Inorganic ;

/** Field mapping. **/
protected String Organic ;

/** Field mapping. **/
protected String Seed ;

/** Field mapping. **/
protected Date DateOfReg ;

protected String strdateOfIncorp ;



protected String Ccode ;

protected String MyPlan ;



public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}
public String getFirstName()
{
  return FirstName;
}
public void setFirstName(final String FirstName)
{
  this.FirstName = FirstName;
}
public String getLastName()
{
  return LastName;
}
public void setLastName(final String LastName)
{
  this.LastName = LastName;
}
public String getCompanyName()
{
  return CompanyName;
}
public void setCompanyName(final String CompanyName)
{
  this.CompanyName = CompanyName;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public String getVillage()
{
  return Village;
}
public void setVillage(final String Village)
{
  this.Village = Village;
}
public String getMandal()
{
  return Mandal;
}
public void setMandal(final String Mandal)
{
  this.Mandal = Mandal;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public int getPincode()
{
  return Pincode;
}
public void setPincode(final int Pincode)
{
  this.Pincode = Pincode;
}
public String getEmail()
{
  return Email;
}
public void setEmail(final String Email)
{
  this.Email = Email;
}
public String getMobile()
{
  return Mobile;
}
public void setMobile(final String Mobile)
{
  this.Mobile = Mobile;
}
public Date getDateOfIncorp()
{
  return DateOfIncorp;
}
public void setDateOfIncorp(final Date DateOfIncorp)
{
  this.DateOfIncorp = DateOfIncorp;
}
public String getGSTNumber()
{
  return GSTNumber;
}
public void setGSTNumber(final String GSTNumber)
{
  this.GSTNumber = GSTNumber;
}
public String getStatus()
{
  return Status;
}
public void setStatus(final String Status)
{
  this.Status = Status;
}
public String getBio()
{
  return Bio;
}
public void setBio(final String Bio)
{
  this.Bio = Bio;
}
public String getBotanical()
{
  return Botanical;
}
public void setBotanical(final String Botanical)
{
  this.Botanical = Botanical;
}
public String getFarmMachinery()
{
  return FarmMachinery;
}
public void setFarmMachinery(final String FarmMachinery)
{
  this.FarmMachinery = FarmMachinery;
}
public String getInorganic()
{
  return Inorganic;
}
public void setInorganic(final String Inorganic)
{
  this.Inorganic = Inorganic;
}
public String getOrganic()
{
  return Organic;
}
public void setOrganic(final String Organic)
{
  this.Organic = Organic;
}
public String getSeed()
{
  return Seed;
}
public void setSeed(final String Seed)
{
  this.Seed = Seed;
}
public Date getDateOfReg()
{
  return DateOfReg;
}
public void setDateOfReg(final Date DateOfReg)
{
  this.DateOfReg = DateOfReg;
}
public String getStrdateOfIncorp() {
	return strdateOfIncorp;
}
public void setStrdateOfIncorp(String strdateOfIncorp) {
	this.strdateOfIncorp = strdateOfIncorp;
}



public String getCcode() {
	return Ccode;
}
public void setCcode(String ccode) {
	Ccode = ccode;
}
public String getMyPlan() {
	return MyPlan;
}
public void setMyPlan(String myPlan) {
	MyPlan = myPlan;
}
@Override
public String toString() {
	return "SupplierReg [Id=" + Id + ", TokenId=" + TokenId + ", FirstName=" + FirstName + ", LastName=" + LastName
			+ ", CompanyName=" + CompanyName + ", Address=" + Address + ", Village=" + Village + ", Mandal=" + Mandal
			+ ", District=" + District + ", State=" + State + ", Pincode=" + Pincode + ", Email=" + Email + ", Mobile="
			+ Mobile + ", DateOfIncorp=" + DateOfIncorp + ", GSTNumber=" + GSTNumber + ", Status=" + Status + ", Bio="
			+ Bio + ", Botanical=" + Botanical + ", FarmMachinery=" + FarmMachinery + ", Inorganic=" + Inorganic
			+ ", Organic=" + Organic + ", Seed=" + Seed + ", DateOfReg=" + DateOfReg + ", strdateOfIncorp="
			+ strdateOfIncorp + "]";
}




}