package com.aurospaces.neighbourhood.bean;


import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 *
 * @author autogenerated
 */



public class TraderTransactions 
{

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
protected int SNo   = 0;

/** Field mapping. **/
protected String CropName ;

/** Field mapping. **/
protected String TokenId ;



/** Field mapping. **/
protected String Variety ;

/** Field mapping. **/
protected String Quantity ;

/** Field mapping. **/
protected String Units ;



/** Field mapping. **/
protected String Comment ;

/** Field mapping. **/
protected String AskPrice ;

/** Field mapping. **/
protected String TransactionType ;

/** Field mapping. **/
protected Date Date ;

/** Field mapping. **/
protected String Status ;

protected String EDD; 

protected String strEDD;



public int getSNo()
{
  return SNo;
}
public void setSNo(final int SNo)
{
  this.SNo = SNo;
}
public String getCropName()
{
  return CropName;
}
public void setCropName(final String CropName)
{
  this.CropName = CropName;
}
public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}

public String getVariety()
{
  return Variety;
}
public void setVariety(final String Variety)
{
  this.Variety = Variety;
}
public String getQuantity()
{
  return Quantity;
}
public void setQuantity(final String Quantity)
{
  this.Quantity = Quantity;
}
public String getUnits()
{
  return Units;
}
public void setUnits(final String Units)
{
  this.Units = Units;
}

public String getComment()
{
  return Comment;
}
public void setComment(final String Comment)
{
  this.Comment = Comment;
}
public String getAskPrice()
{
  return AskPrice;
}
public void setAskPrice(final String AskPrice)
{
  this.AskPrice = AskPrice;
}
public String getTransactionType()
{
  return TransactionType;
}
public void setTransactionType(final String TransactionType)
{
  this.TransactionType = TransactionType;
}
public Date getDate()
{
  return Date;
}
public void setDate(final Date Date)
{
  this.Date = Date;
}
public String getStatus()
{
  return Status;
}
public void setStatus(final String Status)
{
  this.Status = Status;
}


public String getEDD() {
	return EDD;
}
public void setEDD(String eDD) {
	EDD = eDD;
}
public String getStrEDD() {
	return strEDD;
}
public void setStrEDD(String strEDD) {
	this.strEDD = strEDD;
}



}