package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class TraderReg 
{

		 /** Field mapping. **/
protected int Id   = 0;

/** Field mapping. **/
protected String TokenId ;

/** Field mapping. **/
protected String FirstName ;

/** Field mapping. **/
protected String LastName ;

/** Field mapping. **/
protected String CompanyName ;

/** Field mapping. **/
protected String Status ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected String Village ;

/** Field mapping. **/
protected String Mandal ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected int Pincode ;

/** Field mapping. **/
protected String Email ;

/** Field mapping. **/
protected String Mobile ;

/** Field mapping. **/
protected String DateOfIncorp ;

/** Field mapping. **/
protected String GSTNumber ;

/** Field mapping. **/
protected String Crops ;

/** Field mapping. **/
protected String Vegetables ;

/** Field mapping. **/
protected String AniHusbandry ;

/** Field mapping. **/
protected String Dairy,strdateOfIncorp ;

/** Field mapping. **/
protected Date DateOfReg ;


protected String Ccode ;

protected String MyPlan ;

protected String distance ;


public String getStrdateOfIncorp() {
	return strdateOfIncorp;
}
public void setStrdateOfIncorp(String strdateOfIncorp) {
	this.strdateOfIncorp = strdateOfIncorp;
}
public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}
public String getFirstName()
{
  return FirstName;
}
public void setFirstName(final String FirstName)
{
  this.FirstName = FirstName;
}
public String getLastName()
{
  return LastName;
}
public void setLastName(final String LastName)
{
  this.LastName = LastName;
}
public String getCompanyName()
{
  return CompanyName;
}
public void setCompanyName(final String CompanyName)
{
  this.CompanyName = CompanyName;
}
public String getStatus()
{
  return Status;
}
public void setStatus(final String Status)
{
  this.Status = Status;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public String getVillage()
{
  return Village;
}
public void setVillage(final String Village)
{
  this.Village = Village;
}
public String getMandal()
{
  return Mandal;
}
public void setMandal(final String Mandal)
{
  this.Mandal = Mandal;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public int getPincode()
{
  return Pincode;
}
public void setPincode(final int Pincode)
{
  this.Pincode = Pincode;
}
public String getEmail()
{
  return Email;
}
public void setEmail(final String Email)
{
  this.Email = Email;
}
public String getMobile()
{
  return Mobile;
}
public void setMobile(final String Mobile)
{
  this.Mobile = Mobile;
}

public String getGSTNumber()
{
  return GSTNumber;
}
public void setGSTNumber(final String GSTNumber)
{
  this.GSTNumber = GSTNumber;
}
public String getCrops()
{
  return Crops;
}
public void setCrops(final String Crops)
{
  this.Crops = Crops;
}
public String getVegetables()
{
  return Vegetables;
}
public void setVegetables(final String Vegetables)
{
  this.Vegetables = Vegetables;
}
public String getAniHusbandry()
{
  return AniHusbandry;
}
public void setAniHusbandry(final String AniHusbandry)
{
  this.AniHusbandry = AniHusbandry;
}
public String getDairy()
{
  return Dairy;
}
public void setDairy(final String Dairy)
{
  this.Dairy = Dairy;
}
public Date getDateOfReg()
{
  return DateOfReg;
}
public void setDateOfReg(final Date DateOfReg)
{
  this.DateOfReg = DateOfReg;
}
public String getCcode() {
	return Ccode;
}
public void setCcode(String ccode) {
	Ccode = ccode;
}
public String getMyPlan() {
	return MyPlan;
}
public void setMyPlan(String myPlan) {
	MyPlan = myPlan;
}
public String getDistance() {
	return distance;
}
public void setDistance(String distance) {
	this.distance = distance;
}



public String getDateOfIncorp() {
	return DateOfIncorp;
}
public void setDateOfIncorp(String dateOfIncorp) {
	DateOfIncorp = dateOfIncorp;
}
@Override
public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + Id;
	return result;
}
@Override
public boolean equals(Object obj) {
	if (this == obj)
		return true;
	if (obj == null)
		return false;
	if (getClass() != obj.getClass())
		return false;
	TraderReg other = (TraderReg) obj;
	if (Id != other.Id)
		return false;
	return true;
}




}