package com.aurospaces.neighbourhood.bean;

/**
 *
 * @author autogenerated
 */



public class Units 
{

/** Field mapping. **/
protected String Category ;

/** Field mapping. **/
protected String Unit ;

public String getCategory()
{
  return Category;
}
public void setCategory(final String Category)
{
  this.Category = Category;
}
public String getUnit()
{
  return Unit;
}
public void setUnit(final String Unit)
{
  this.Unit = Unit;
}

}