package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class VegPrices 
{


protected int Id   = 0;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String Market ;

/** Field mapping. **/
protected String Vegetables ;

/** Field mapping. **/
protected String LocalRate,pincode ;



public String getPincode() {
	return pincode;
}
public void setPincode(String pincode) {
	this.pincode = pincode;
}
/** Field mapping. **/
protected Date Date ;

public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getMarket()
{
  return Market;
}
public void setMarket(final String Market)
{
  this.Market = Market;
}
public String getVegetables()
{
  return Vegetables;
}
public void setVegetables(final String Vegetables)
{
  this.Vegetables = Vegetables;
}
public String getLocalRate()
{
  return LocalRate;
}
public void setLocalRate(final String LocalRate)
{
  this.LocalRate = LocalRate;
}
public Date getDate()
{
  return Date;
}
public void setDate(final Date Date)
{
  this.Date = Date;
}

}