package com.aurospaces.neighbourhood.bean;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class VegPrices 
{


protected int Id   = 0;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String Market ;

/** Field mapping. **/
protected String Vegetables ;

/** Field mapping. **/
protected String LocalRate ;

/** Field mapping. **/
protected Date Date ;

public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getMarket()
{
  return Market;
}
public void setMarket(final String Market)
{
  this.Market = Market;
}
public String getVegetables()
{
  return Vegetables;
}
public void setVegetables(final String Vegetables)
{
  this.Vegetables = Vegetables;
}
public String getLocalRate()
{
  return LocalRate;
}
public void setLocalRate(final String LocalRate)
{
  this.LocalRate = LocalRate;
}
public Date getDate()
{
  return Date;
}
public void setDate(final Date Date)
{
  this.Date = Date;
}

}