package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class VendorReg 
{


protected int Id   = 0;

/** Field mapping. **/
protected String TokenId ;

/** Field mapping. **/
protected String FirstName ;

/** Field mapping. **/
protected String LastName ;

/** Field mapping. **/
protected String CompanyName ;

/** Field mapping. **/
protected String Status ;

/** Field mapping. **/
protected String Address ;

/** Field mapping. **/
protected String Village ;

/** Field mapping. **/
protected String Mandal ;

/** Field mapping. **/
protected String District ;

/** Field mapping. **/
protected String State ;

/** Field mapping. **/
protected int Pincode ;

/** Field mapping. **/
protected String Email ;

/** Field mapping. **/
protected String Mobile ;

/** Field mapping. **/
protected String DateOfIncorp ;

/** Field mapping. **/
protected String GSTNumber ;

/** Field mapping. **/
protected String Vegetables ;

/** Field mapping. **/
protected String AniHus ;

/** Field mapping. **/
protected String Dairy,strdateOfIncorp ;

public String getStrdateOfIncorp() {
	return strdateOfIncorp;
}
public void setStrdateOfIncorp(String strdateOfIncorp) {
	this.strdateOfIncorp = strdateOfIncorp;
}
/** Field mapping. **/
protected Date DateOfReg ;

public int getId()
{
  return Id;
}
public void setId(final int Id)
{
  this.Id = Id;
}
public String getTokenId()
{
  return TokenId;
}
public void setTokenId(final String TokenId)
{
  this.TokenId = TokenId;
}
public String getFirstName()
{
  return FirstName;
}
public void setFirstName(final String FirstName)
{
  this.FirstName = FirstName;
}
public String getLastName()
{
  return LastName;
}
public void setLastName(final String LastName)
{
  this.LastName = LastName;
}
public String getCompanyName()
{
  return CompanyName;
}
public void setCompanyName(final String CompanyName)
{
  this.CompanyName = CompanyName;
}
public String getStatus()
{
  return Status;
}
public void setStatus(final String Status)
{
  this.Status = Status;
}
public String getAddress()
{
  return Address;
}
public void setAddress(final String Address)
{
  this.Address = Address;
}
public String getVillage()
{
  return Village;
}
public void setVillage(final String Village)
{
  this.Village = Village;
}
public String getMandal()
{
  return Mandal;
}
public void setMandal(final String Mandal)
{
  this.Mandal = Mandal;
}
public String getDistrict()
{
  return District;
}
public void setDistrict(final String District)
{
  this.District = District;
}
public String getState()
{
  return State;
}
public void setState(final String State)
{
  this.State = State;
}
public int getPincode()
{
  return Pincode;
}
public void setPincode(final int Pincode)
{
  this.Pincode = Pincode;
}
public String getEmail()
{
  return Email;
}
public void setEmail(final String Email)
{
  this.Email = Email;
}
public String getMobile()
{
  return Mobile;
}
public void setMobile(final String Mobile)
{
  this.Mobile = Mobile;
}
public String getDateOfIncorp()
{
  return DateOfIncorp;
}
public void setDateOfIncorp(final String DateOfIncorp)
{
  this.DateOfIncorp = DateOfIncorp;
}
public String getGSTNumber()
{
  return GSTNumber;
}
public void setGSTNumber(final String GSTNumber)
{
  this.GSTNumber = GSTNumber;
}
public String getVegetables()
{
  return Vegetables;
}
public void setVegetables(final String Vegetables)
{
  this.Vegetables = Vegetables;
}
public String getAniHus()
{
  return AniHus;
}
public void setAniHus(final String AniHus)
{
  this.AniHus = AniHus;
}
public String getDairy()
{
  return Dairy;
}
public void setDairy(final String Dairy)
{
  this.Dairy = Dairy;
}
public Date getDateOfReg()
{
  return DateOfReg;
}
public void setDateOfReg(final Date DateOfReg)
{
  this.DateOfReg = DateOfReg;
}

}